/* eslint-disable max-len */
const product_seeds = [
    {
        title: 'Doctor Strange 2',
        genre: 'action, adventure',
        synopsis: 'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse',
        author: 'Sam Raimi',
        units: 5,
        book: false,
        movie: true,
        tv_show: false,
        sell: true,
        rent: false,
        sell_price: 20,
        rent_price: null,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: 'John Wick 3',
        genre: 'action, adventure',
        synopsis: 'John Wick is declared excommunicado and a hefty bounty is set on him after he murders an international crime lord. He sets out to seek help to save himself from ruthless hitmen and bounty hunters.',
        author: 'Chad Stahelski',
        units: 10,
        book: false,
        movie: true,
        tv_show: false,
        sell: true,
        rent: true,
        sell_price: 20,
        rent_price: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: 'Minions 2',
        genre: 'comedy, adventure',
        synopsis: 'In the 1970s, young Gru tries to join a group of supervillains called the Vicious 6 after they oust their leader -- the legendary fighter Wild Knuckles. When the interview turns disastrous, Gru and his Minions go on the run with the Vicious 6 hot on their tails. Luckily, he finds an unlikely source for guidance -- Wild Knuckles himself -- and soon discovers that even bad guys need a little help from their friends.',
        author: 'Kyle Balda',
        units: 3,
        book: false,
        movie: true,
        tv_show: false,
        sell: false,
        rent: true,
        sell_price: null,
        rent_price: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: 'Stranger Things',
        genre: 'horror, action, adventure',
        synopsis: 'In 1980s Indiana, a group of young friends witness supernatural forces and secret government exploits. As they search for answers, the children unravel a series of extraordinary mysteries.',
        author: 'The Duffer Brothers',
        units: 15,
        book: false,
        movie: false,
        tv_show: true,
        sell: false,
        rent: true,
        sell_price: null,
        rent_price: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: 'Dark',
        genre: 'si-fi, action, adventure',
        synopsis: 'When two children go missing in a small German town, its sinful past is exposed along with the double lives and fractured relationships that exist among four families as they search for the kids. The mystery-drama series introduces an intricate puzzle filled with twists that includes a web of curious characters, all of whom have a connection to the town`s troubled history -- whether they know it or not. The story includes supernatural elements that tie back to the same town in 1986. "Dark" represents the first German original series produced for Netflix.',
        author: 'Baran bo Odar',
        units: 8,
        book: false,
        movie: false,
        tv_show: true,
        sell: true,
        rent: false,
        sell_price: 40,
        rent_price: null,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: 'Loki',
        genre: 'action, adventure',
        synopsis: 'Loki, the God of Mischief, steps out of his brother`s shadow to embark on an adventure that takes place after the events of "Avengers: Endgame."',
        author: 'Michael Waldron',
        units: 3,
        book: false,
        movie: false,
        tv_show: true,
        sell: true,
        rent: true,
        sell_price: 30,
        rent_price: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: 'Fast and Slow',
        genre: 'Non-fiction, Psychology',
        synopsis: 'Thinking, Fast and Slow is a 2011 book by psychologist Daniel Kahneman. The book`s main thesis is that of a dichotomy between two modes of thought: "System 1" is fast, instinctive and emotional; "System 2" is slower, more deliberative, and more logical.',
        author: 'Daniel Kahneman',
        units: 6,
        book: true,
        movie: false,
        tv_show: false,
        sell: true,
        rent: false,
        sell_price: 50,
        rent_price: null,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: 'Harry Potter Box',
        genre: 'adventure, action',
        synopsis: 'Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry.',
        author: 'J. K. Rowling',
        units: 3,
        book: true,
        movie: false,
        tv_show: false,
        sell: true,
        rent: false,
        sell_price: 250,
        rent_price: null,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: 'The Call of Cthulhu',
        genre: 'horror',
        synopsis: '"The Call of Cthulhu" is a short story by American writer H. P. Lovecraft. Written in the summer of 1926, it was first published in the pulp magazine Weird Tales in February 1928.',
        author: 'H. P. Lovecraft',
        units: 5,
        book: true,
        movie: false,
        tv_show: false,
        sell: true,
        rent: true,
        sell_price: 20,
        rent_price: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

export default product_seeds;
